version: "3.8"

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # volumes:
    #   - pgdata:/var/lib/postgresql/data


  web:
    container_name: ${DOCKERHUB_REPOSITORY_NAME}_backend
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY_NAME}
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_ECHO=${DB_ECHO}
      - SCRAPING_INTERVAL_SECONDS=${SCRAPING_INTERVAL_SECONDS}
      - BOT_TOKEN=${BOT_TOKEN}
    command: bash -c "alembic upgrade head && python src/main.py"
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

# volumes:
#   pgdata:
